### PR TITLE
build: update internal dependency versions on release PRs

### PR DESCRIPTION
**Pull request by dobladez**
### What does this PR do?
Improve release scripts to automatically keep the version inter-dependencies updated on the release PRs.

Example: On the release PR for soql-model,  the script now updates soql-builder-ui's package.json to depend on the new version.

### What issues does this PR fix or reference?
W-8700164

### CODE REVIEW

**Comment by praksb** [comment]
Do we really want to automate this or continue to keep this step manual? My concern is that if this would potentially prevent soql-model only changes to be blocked until the corresponding changes in soql-builder-ui is complete since otherwise there is a possibility of build break or functionality break in soql-builder-ui.

**Comment by dobladez** [comment]
> Do we really want to automate this or continue to keep this step manual? My concern is that if this would potentially prevent soql-model only changes to be blocked until the corresponding changes in soql-builder-ui is complete since otherwise there is a possibility of build break or functionality break in soql-builder-ui.

That's a good point. What's the most common case? Is it to bump the deps together on release? or release independently?
May be we should default to the common case, leaving the option to manually override it.

Either way, having the separate "release" PRs allows us to override the changes before merging.

If we decide not to update the deps on the release PRs on every commit to `main`, one could run the same script locally, or we could also have the logic in a separate gh action and trigger it manually.

**Comment by dehru** [comment]
We sure do a lot of work to keep a mono-repo.  Are we sure we don't wanna just have separate repos for:

- soql-builder-ui ( includes soql-model library )
- soql-data-view
- soql-common

**Comment by jonnyhork** [comment]
I was just gonna say the same thing as @dehru 
How badly or how soon do we want to convert soql-model to a library in builder-ui? Because once we do that, then this automation wont be needed right?

**Comment by praksb** [comment]
It seems like we are complicating our automation. Since soql-model is used only by the soql-builder-ui why do we even have to publish soql-model to npm? Instead, can we just take a source dependency on this like @jonnyhork suggested.

**Comment by dobladez** [comment]
Sounds good. If we all agree on getting rid of the monorepo, let's do it :-). We can split soql-tooling into 3 separate repos like @dehru mentioned.

I just realized VSCode extension depends on soql-model. We might be able to refactor to cut that dependency.

**Comment by dobladez** [comment]
Note: the workflow files (under `.github/workflows/*`) are all pretty much the same: only the package name changes. There's not built-in mechanism to parameterize and reuse gh workflows.

**Review by jonnyhork — APPROVED** [review]

**Pull request merged**
