### PR TITLE
feat: provide accessible labels

### PR DESCRIPTION
**Pull request by dehru**
### What does this PR do?
This adds labels to some of the more complex soql builder components.  For instance, the triplet WHERE inputs and ORDER BY inputs.  According to the accessibility folks here at salesforce, we need to use hidden labels instead of the aria-label attribute.

### What issues does this PR fix or reference?
@W-8984214@

Interestingly, LWC automatically adds unique id's to elements if you give them an id.  So i don't need to worry about id collision.

Screen Shot 2021-03-11 at 2 31 47 PM

### CODE REVIEW

**Comment by dehru** [comment]
I'm updating this as the accessibility team says that aria-label is not yet supported and we should use actual hidden labels.

**Comment by jgellin-sf** [comment]
QA failed. The labels are successfully inserted into the DOM, but they are not being read by VoiceOver.

**Comment by dehru** [comment]
We are punting on accessibility for now.

**Comment by jonnyhork** [comment]
I'm curious why we wouldn't at least add the `aria-label` attributes? We saw that they worked for us with Voice Over and they do not effect function in any way. Even though the A11y team suggested a different approach , adding the `aria-labels` _only adds value_ in the meantime, and that could impact at least one or more people in the future.
CC @smaddox-sf @dehru

**Pull request closed without merging**
